[package]
name = "sadraskol"
version = "0.1.0"
authors = ["Thomas Bracher <thomas.bracher@cpe.fr>"]
edition = "2018"

default-run = "sadraskol"

[dependencies]
actix-identity = "0.2.1"
actix-rt = "1.1.1"
actix-web = "2.0.0"
actix = "0.10.0-alpha.2"
r2d2 = "0.8.9"
postgres = { version = "0.17.5", features = ["with-uuid-0_8", "with-chrono-0_4"] }
postgres-derive = "0.4.0"
chrono = { version = "0.4.15", features = ["serde"] }
serde = { version = "1.0.115", features = ["derive"] }
serde_json = "1.0.57"
uuid = { version = "0.8.1", features = ["serde", "v4"] }
env_logger = "0.7.1"
rand = "0.7.3"
pulldown-cmark = "0.7.2"
unidecode = "0.3.0"
toml = "0.5.6"
log = "0.4.11"
futures = "0.3.5"
askama = "0.10.3"

[features]
production = []
