[package]
name = "sadraskol"
version = "0.1.0"
authors = ["Thomas Bracher <thomas.bracher@cpe.fr>"]
edition = "2018"

[dependencies]
actix-identity = "0.2"
actix-rt = "1.0"
actix-web = "2.0"
r2d2 = "0.8.7"
postgres = { version = "0.17.0-alpha.2", features = ["with-uuid-0_8", "with-chrono-0_4"]}
postgres-openssl = "0.3.0-alpha.2"
postgres-derive = "0.4.0-alpha.1"
chrono = { version = "0.4", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
uuid = { version = "0.8", features = ["serde", "v4"] }
env_logger = "0.7.1"
rand = "0.7.2"
pulldown-cmark = "0.6.1"
unidecode = "0.3.0"
openssl = "0.10"
toml = "0.5"
log = "0.4"
futures = "0.3.1"
askama = "0.8"

[features]
production = []