[package]
name = "sadraskol"
version = "0.1.0"
authors = ["Thomas Bracher <thomas.bracher@cpe.fr>"]
edition = "2018"

[dependencies]
actix-identity = "0.1.0"
actix-web = "1.0.5"
r2d2 = "0.8.5"
postgres = { version = "0.15", features = ["with-serde_json", "with-chrono", "with-uuid"] }
postgres-derive = "0.3.3"
chrono = { version = "0.4", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.40"
uuid = { version = "0.5", features = ["serde", "v4"] }
env_logger = "0.6.2"
either = "1.5.2"
rand = "0.7.0"
pulldown-cmark = "0.5.3"