name: Build site

on:
  push:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup git
      run: |
        git config --global user.email "bot@sadraskol.com"
        git config --global user.name "Sadbot"

    - name: Update repository
      run: |
        git fetch

    - name: Initialize output directory
      run: git worktree add ./dist remotes/origin/master

    - name: Run gen
      uses: actions-rs/cargo@v1
      with:
        command: run

    - name: Publish
      run: |
        cd dist
        git add . 
        git commit -m "regenerate of dev"
        git push "https://${GITHUB_ACTOR}:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git" HEAD:master
